const quotes =[
  {quote: "What you leave behind is not what is engraved in stone monuments, but what is woven into the lives of others.", authoer:"Pericles"},
  {quote: "Education consists mainly of what we have unlearned.", author: "Mark Twain"},
  {quote: "I've never let my schooling interfere with my education.", author: "Mark Twain"},
  {quote: "There is no such thing as a tree. No such thing as a fish. A tree is a strategy. Wood is a strategy. Fruit is a strategy. A fish is also a strategy.", author: "Eukaryote Writes Blog"},
  {quote: "A complex system that works is invariably found to have evolved from a simple system that worked. A complex system designed from scratch never works and cannot be patched up to make it work. You have to start over with a working simple system.", author: "John Gall (Systemantics - 1975)"},
  {quote: "I hate quotations. Tell me what YOU know.", author: "Ralph Waldo Emerson"},
  {quote: "There is neither good, nor bad, but thinking makes it so.", author: "Hamlet"},
  {quote: "It is the arrogance of every age to believe that yesterday was calm.", author: "Tom Peters"},
  {quote: "Inquire within.", author: "Anonymous"},
  {quote: "Community precedes commerce.", author: "John Hagel"},
  {quote: "To measure is to know.", author: "Lord Kelvin"},
  {quote: "There is much ruin in a nation.", author: "Adam Smith"},
  {quote: "Waste flows downstream. But we all live downstream too.", author: "Anonymous"},
  {quote: "Some people become vandals in order to make the world a better looking place.", author: "Banksy"},
  {quote: "Strength is the outcome of need.", author: "H.G. Wells"},
  {quote: "Our ignorance is not as vast as our failure to use what we know.", author: "M. King Hubbert"},
  {quote: "We are doomed to make choices. This is life's greatest paradox.", author: "Wayne Dyer"},
  {quote: "We do not see things as they are. We see things as we are.", author: "Talmud"},
  {quote: "Life is change. Growth is optional. Choose wisely.", author: "Karen Kaiser Clark"},
  {quote: "If you want to get somewhere fast, go alone. If you want to get far, go together.", author: "African proverb"},
  {quote: "Man can do what he wants but he cannot want what he wants.", author: "Arthur Schopenhauer"},
  {quote: "As soil goes, so goes civilizaiton.", author: "Woody Tasch"},
  {quote: "There are two ways to be rich: one is by acquiring much, the other is by desiring little.", author: "Jackie French Koller"},
]

const colors = [
  '#16a085',
  '#27ae60',
  '#2c3e50',
  '#f39c12',
  '#e74c3c',
  '#9b59b6',
  '#FB6964',
  '#472E32',
  '#BDBB99',
  '#77B1A9',
  '#73A857',
  'crimson',
  'dodgerblue',
  'gold',
  'turquoise',
  'hotpink',
  'rebeccapurple',
  'seagreen',
  'lightseagreen',
];
